// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TB.Models;

namespace TB.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20180521024547_hosp")]
    partial class hosp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TB.Models.TBL_MS_AMPUR", b =>
                {
                    b.Property<string>("AMPUR_ID");

                    b.Property<string>("AMPUR_NAME_EN");

                    b.Property<string>("AMPUR_NAME_TH");

                    b.Property<string>("CHANGWAT_ID");

                    b.Property<decimal>("LATITUDE");

                    b.Property<decimal>("LONGTITUDE");

                    b.Property<string>("POLYGON");

                    b.Property<string>("STATUS");

                    b.HasKey("AMPUR_ID");

                    b.ToTable("TBL_MS_AMPUR");
                });

            modelBuilder.Entity("TB.Models.TBL_MS_CHANGWAT", b =>
                {
                    b.Property<string>("CHANGWAT_ID");

                    b.Property<string>("CHANGWAT_NAME_EN");

                    b.Property<string>("CHANGWAT_NAME_TH");

                    b.Property<string>("COUNTRY_ID");

                    b.Property<string>("NHSO_ID");

                    b.Property<string>("ODPC_ID");

                    b.Property<string>("STATUS");

                    b.Property<string>("ZONE");

                    b.HasKey("CHANGWAT_ID");

                    b.ToTable("TBL_MS_CHANGWAT");
                });

            modelBuilder.Entity("TB.Models.TBL_MS_DEFINE_CODE", b =>
                {
                    b.Property<string>("MAJOR");

                    b.Property<string>("MINOR");

                    b.Property<string>("CODE1");

                    b.Property<string>("DESCRIPTION_EN");

                    b.Property<string>("DESCRIPTION_TH");

                    b.Property<string>("FLAG");

                    b.Property<string>("NHSO_CODE");

                    b.Property<string>("REMARK");

                    b.Property<string>("SEQUENCE");

                    b.HasKey("MAJOR", "MINOR");

                    b.ToTable("TBL_MS_DEFINE_CODE");
                });

            modelBuilder.Entity("TB.Models.TBL_MS_HOSP_CODE", b =>
                {
                    b.Property<string>("ORG_ID");

                    b.Property<string>("ADDR");

                    b.Property<string>("AMPUR");

                    b.Property<string>("BED");

                    b.Property<string>("CHANGWAT");

                    b.Property<string>("DEPARTMENT");

                    b.Property<string>("FAX");

                    b.Property<string>("IS_CULTURE_TREAT");

                    b.Property<string>("IS_CUL_LIQUID");

                    b.Property<string>("IS_CUL_SOLID");

                    b.Property<string>("IS_DST_LIQUID");

                    b.Property<string>("IS_DST_SOLID");

                    b.Property<string>("IS_DST_TREAT");

                    b.Property<string>("IS_MDR_TREAT");

                    b.Property<string>("IS_MOLECULAR_TREAT");

                    b.Property<string>("IS_MOL_LPA");

                    b.Property<string>("IS_MOL_XPERT");

                    b.Property<string>("IS_NHSO_ORG");

                    b.Property<string>("IS_OUTOF_TBCM");

                    b.Property<string>("MU");

                    b.Property<string>("NAME_EN");

                    b.Property<string>("NAME_TH");

                    b.Property<string>("NHSO_ID");

                    b.Property<string>("ODPC_ID");

                    b.Property<string>("ORG_ID_9");

                    b.Property<string>("ORG_LEVEL");

                    b.Property<string>("ORG_TYPE");

                    b.Property<string>("ORG_TYPE_NHSO");

                    b.Property<string>("PHO_ID");

                    b.Property<string>("SSO_ID");

                    b.Property<string>("STATUS");

                    b.Property<string>("TAMBON");

                    b.Property<string>("TEL");

                    b.Property<string>("hmain_id");

                    b.HasKey("ORG_ID");

                    b.ToTable("TBL_MS_HOSP_CODE");
                });

            modelBuilder.Entity("TB.Models.TBL_MS_TAMBON", b =>
                {
                    b.Property<string>("TAMBON_ID");

                    b.Property<string>("AMPUR_ID");

                    b.Property<decimal>("LATITUDE");

                    b.Property<decimal>("LONGTITUDE");

                    b.Property<string>("POLYGON");

                    b.Property<string>("STATUS");

                    b.Property<string>("TAMBON_NAME_EN");

                    b.Property<string>("TAMBON_NAME_TH");

                    b.HasKey("TAMBON_ID");

                    b.ToTable("TBL_MS_TAMBON");
                });

            modelBuilder.Entity("TB.Models.TBL_REQUEST_USER", b =>
                {
                    b.Property<int>("REQUEST_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CID");

                    b.Property<DateTime>("CREATED_DATE");

                    b.Property<string>("EMAIL");

                    b.Property<string>("FNAME");

                    b.Property<string>("LNAME");

                    b.Property<string>("ORG_ID");

                    b.Property<string>("PHONE");

                    b.Property<string>("REGIS_BY");

                    b.Property<string>("REGIS_DATE");

                    b.Property<string>("REQUEST_DATE");

                    b.Property<string>("REQUEST_STATUS");

                    b.Property<string>("TITLE_ID");

                    b.Property<DateTime>("UPDATED_DATE");

                    b.HasKey("REQUEST_ID");

                    b.ToTable("TBL_REQUEST_USER");
                });

            modelBuilder.Entity("TB.Models.TBL_REQUEST_USER_GROUP", b =>
                {
                    b.Property<int>("REQUEST_GROUP_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GROUP_ID");

                    b.Property<string>("IS_VALID");

                    b.Property<int>("REQUEST_ID");

                    b.HasKey("REQUEST_GROUP_ID");

                    b.ToTable("TBL_REQUEST_USER_GROUP");
                });
#pragma warning restore 612, 618
        }
    }
}
