// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using System;
using TB.Models;

namespace TB.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TB.Models.TBL_MS_AMPUR", b =>
                {
                    b.Property<string>("AMPUR_ID");

                    b.Property<string>("AMPUR_NAME_EN");

                    b.Property<string>("AMPUR_NAME_TH");

                    b.Property<string>("CHANGWAT_ID");

                    b.Property<decimal>("LATITUDE");

                    b.Property<decimal>("LONGTITUDE");

                    b.Property<string>("POLYGON");

                    b.Property<string>("STATUS");

                    b.HasKey("AMPUR_ID");

                    b.ToTable("TBL_MS_AMPUR");
                });

            modelBuilder.Entity("TB.Models.TBL_MS_CHANGWAT", b =>
                {
                    b.Property<string>("CHANGWAT_ID");

                    b.Property<string>("CHANGWAT_NAME_EN");

                    b.Property<string>("CHANGWAT_NAME_TH");

                    b.Property<string>("COUNTRY_ID");

                    b.Property<string>("NHSO_ID");

                    b.Property<string>("ODPC_ID");

                    b.Property<string>("STATUS");

                    b.Property<string>("ZONE");

                    b.HasKey("CHANGWAT_ID");

                    b.ToTable("TBL_MS_CHANGWAT");
                });

            modelBuilder.Entity("TB.Models.TBL_MS_TAMBON", b =>
                {
                    b.Property<string>("TAMBON_ID");

                    b.Property<string>("AMPUR_ID");

                    b.Property<decimal>("LATITUDE");

                    b.Property<decimal>("LONGTITUDE");

                    b.Property<string>("POLYGON");

                    b.Property<string>("STATUS");

                    b.Property<string>("TAMBON_NAME_EN");

                    b.Property<string>("TAMBON_NAME_TH");

                    b.HasKey("TAMBON_ID");

                    b.ToTable("TBL_MS_TAMBON");
                });
#pragma warning restore 612, 618
        }
    }
}
